[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r python-ai/requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python3 python-ai/app.py"
